// Golden-data cross-check: TS GameState.toPlanes(17) must match Python
// gomoku/game.py:to_planes byte-for-byte. The fixture is generated by
// scripts under /Users/jason/.claude/jobs/97325735/gen_planes_golden.py
// and is committed as golden_planes.json next to this test.
import { describe, expect, it } from "vitest";
import golden from "./golden_planes.json";

import { GameState, strToAction } from "../game";

interface Scenario {
  moves: string[];
  planes: number[];
}

describe("17-plane history featurizer (Python parity)", () => {
  it.each((golden as Scenario[]).map((s, i) => [i, s]))(
    "scenario %i (%o moves)",
    (_i, scenario) => {
      let s = GameState.initial();
      for (const mv of scenario.moves) s = s.apply(strToAction(mv));
      const planes = s.toPlanes(17);
      expect(planes.length).toBe(17 * 81);
      for (let k = 0; k < planes.length; k++) {
        if (planes[k] !== scenario.planes[k]) {
          throw new Error(
            `plane mismatch at idx ${k}: ts=${planes[k]} py=${scenario.planes[k]}` +
              ` (moves=${scenario.moves.join(",")})`,
          );
        }
      }
    },
  );
});
